services:
  wordpress:
    build:
      context: './Dockerfile/wordpress'
    image: wordpress:f25
    container_name: wordpress_w
    volumes:
      - '.:/var/www/html'
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - database
  database:
    build:
      context: './Dockerfile/db'
    image: mariadb:f25
    container_name: database_w
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060