name: docker-wordpress-node
services:
  wordpress:
    build:
      context: './docker/wordpress'
    container_name: wordpress
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql_wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - wordpress_db_vol:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    expose:
      - 3306
      - 33060

volumes:
  wordpress_db_vol:
