services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './mysql_data:/var/lib/mysql'
    ports:
      - "3360:3306"
    networks:
      - php_network
networks:
  php_network:
    driver: bridge
    name: php_network
