name: wp

services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - wp_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3306:3306'
    networks:
      - default
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always

  wp:
    build:
      context: .
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./workdir:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - '8000:80'
    networks:
      - default
    working_dir: '/var/www/html'
    restart: always
    user: 1000:1000

networks:
  default:
    name: wp

volumes:
  wp_vol:
